INFRA-240: Update autorunner zip file name
mekomsolutions/appliance-os pull request #18
Opened 2021-04-22 01:53 UTC by chinzou

https://mekomsolutions.atlassian.net/browse/INFRA-240

2021-04-22 06:45 UTC, rbuisson requested changes

2021-04-22 06:45 UTC, rbuisson commented on roles/usb_autorunner/files/autorunner.sh.j2
> +  echo "Secret key file ‘$SECRET_KEY_FILENAME’ is missing at path $MOUNT_POINT/"
Looks like this is not exactly single quote but some other character.
Could you make sure those are " ' "

2021-04-22 06:45 UTC, rbuisson commented on roles/usb_autorunner/files/autorunner.sh.j2
Why this space?

2021-04-22 06:45 UTC, rbuisson commented on roles/usb_autorunner/files/autorunner.sh.j2
>  AUTORUN_CONTENT_PATH={{ usb_autorunner_install_path }}/workdir
This would be better renamed: `AUTORUNNER_WORKDIR`

2021-04-23 14:14 UTC, rbuisson requested changes

2021-04-23 14:14 UTC, rbuisson commented on roles/usb_autorunner/files/autorunner.sh.j2
> +  unzip -oq $AUTORUNNER_WORKDIR/autorun.zip -d $TEMP_PATH
This is the opposite we should do:
Decrypt on the tmp dir, and then unzip in the workdir.

2021-04-23 14:14 UTC, rbuisson commented on roles/usb_autorunner/files/autorunner.sh.j2
> +  openssl enc -d -aes-256-cbc -pbkdf2 -in $autorun_file_path -out $AUTORUNNER_WORKDIR/autorun.zip -pass file:$AUTORUNNER_WORKDIR/secret.key
Could you change this to:
```
openssl enc -d -aes-256-cbc -md sha256 -in $autorun_file_path -out $AUTORUNNER_WORKDIR/autorun.zip -pass file:$AUTORUNNER_WORKDIR/secret.key
```

Removing `-pbkdf2` as this is not supported in OpenSSL on MacOS :/
Adding `-md sha256`to ensure compatiblity between OpenSSL versions

2021-04-23 16:47 UTC, rbuisson commented on roles/usb_autorunner/tasks/main.yml
> +  shell: openssl aes-256-cbc -pbkdf2 -in {{ temp_test_folder.path }}/autorun.zip -out {{ temp_test_folder.path }}/autorun.zip.enc -pass file:{{ temp_test_folder.path }}/secret.key
You might want to change this to:
```
openssl enc -aes-256-cbc -md sha256 -in {{ temp_test_folder.path }}/autorun.zip -out {{ temp_test_folder.path }}/autorun.zip.enc -pass file:{{ temp_test_folder.path }}/secret.key
```

2021-04-23 16:48 UTC, rbuisson commented on roles/usb_autorunner/tasks/main.yml
> +  shell: openssl aes-256-cbc -pbkdf2 -in {{ temp_test_folder.path }}/autorun.zip -out {{ temp_test_folder.path }}/autorun.zip.enc -pass file:{{ temp_test_folder.path }}/secret.key
(mind the `enc`too)

2021-04-23 16:48 UTC, chinzou commented on roles/usb_autorunner/tasks/main.yml
> +  shell: openssl aes-256-cbc -pbkdf2 -in {{ temp_test_folder.path }}/autorun.zip -out {{ temp_test_folder.path }}/autorun.zip.enc -pass file:{{ temp_test_folder.path }}/secret.key
Ah yes, sure.

2021-04-23 16:54 UTC, merged